batchsize: 32
seed: 1
max_iteration: 10000
report_freq: 1000
model_snapshot_freq: 10000
manager_snapshot_freq: 1000
num_workers: 2
T_cond: 5
lr: 0.001

train_data:
  fn: ./datasets/so3_data.py
  name: SO3rotationSequence
  args:
    data_filename: so3dat_sphere_iResNet.pt
    train: True
    T: 8
    datamode: so3
    pmatnet:

model:
  fn: ./models/seqae.py
  name: SeqAELSTSQ
  args:
    dim_m: 10
    dim_a: 6
    ch_x: 1
    k: 2.
    predictive: True

training_loop:
  fn: ./training_loops.py
  name: loop_seqmodel
  args:
    lr_decay_iter: 40000
    reconst_iter: 0



