batchsize: 32
seed: 1
max_iteration: 100000
report_freq: 1000
model_snapshot_freq: 50000
manager_snapshot_freq: 50000
num_workers: 2
T_cond: 2
lr: 0.0003
reg:
  reg_comm:
  reg_bd:
  reg_inv:
  reg_orth:
  reg_rec: 0 and 1


train_data:
  fn: ./datasets/seq_mnist.py
  name: SequentialMNIST
  args:
    #root: /tmp/datasets/MNIST
    root: /mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST
    train: True
    T: 10
    max_T: 10
    max_angle_velocity_ratio: [-0.5, 0.5]
    max_color_velocity_ratio: [-0.5, 0.5]
    only_use_digit4: True
    backgrnd: False


model:
  fn: ./models/seqae.py
  name: SeqAENeuralM
  args:
    dim_m: 256
    dim_a: 16
    ch_x: 3
    k: 4.
    predictive: True


training_loop:
  fn: ./training_loops.py
  name: loop_seqmodel
  args:
    lr_decay_iter: 40000
    reconst_iter: 50000



