batchsize: 32
seed: 1
max_iteration: 100000
report_freq: 1000
model_snapshot_freq: 100000
manager_snapshot_freq: 100000
num_workers: 2
T_cond: 2
T_pred: 1
lr: 0.0003
reg:
  reg_bd:
  reg_orth:

train_data:
  fn: ./datasets/seq_mnist.py
  name: SequentialMNIST_double
  args:
    #root: /tmp/datasets/MNIST
    root: /mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST
    train: True
    T: 3
    max_T: 9
    max_angle_velocity_ratio: [-0.5, 0.5]
    max_color_velocity_ratio: [-0.5, 0.5]
    only_use_digit4: True
    backgrnd: False
    pair_transition: False
    same_object: False
    fixpos: True

model:
  fn: ./models/seqae.py
  name: SeqAELSTSQ_inner
  args:
    dim_m: 256
    dim_a: 16
    ch_x: 3
    k: 2.
    predictive: True
    detachM: 0
    inner_args:
      normalize: 0
      batchsize: 32
      num_loops: 30
      detach: 1 and 0
      beta: 0
      temperature: 1
      mode: glasso and exact
      lr: 0.1

training_loop:
  fn: ./training_loops.py
  name: loop_seqmodel
  args:
    lr_decay_iter: 40000
    reconst_iter: 0



