kubectl delete pod --field-selector=status.phase=Succeeded
kubectl get pods --field-selector "status.phase=Failed" -o name | xargs kubectl delete


pfkube run --job-name=mstar-inv-reg-zero0-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg0_dmodeorth_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero1-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg0_dmodeorth_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero2-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg0_dmodemix_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero3-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg0_dmodemix_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero4-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=0.1 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg01_dmodeorth_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero5-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=0.1 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg01_dmodeorth_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero6-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=0.1 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg01_dmodemix_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero7-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=0.1 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg01_dmodemix_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero8-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=0.5 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg05_dmodeorth_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero9-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=0.5 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg05_dmodeorth_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero10-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=0.5 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg05_dmodemix_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero11-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=0.5 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg05_dmodemix_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero12-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=1.0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg10_dmodeorth_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero13-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=1.0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg10_dmodeorth_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero14-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=1.0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg10_dmodemix_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero15-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0003 comm_reg=0 inv_reg=1.0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00003_inv_reg10_dmodemix_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero16-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg0_dmodeorth_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero17-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg0_dmodeorth_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero18-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg0_dmodemix_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero19-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg0_dmodemix_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero20-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=0.1 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg01_dmodeorth_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero21-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=0.1 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg01_dmodeorth_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero22-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=0.1 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg01_dmodemix_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero23-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=0.1 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg01_dmodemix_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero24-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=0.5 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg05_dmodeorth_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero25-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=0.5 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg05_dmodeorth_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero26-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=0.5 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg05_dmodemix_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero27-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=0.5 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg05_dmodemix_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero28-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=1.0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg10_dmodeorth_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero29-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=1.0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=orth model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg10_dmodeorth_mnet_mlp2"


pfkube run --job-name=mstar-inv-reg-zero30-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=1.0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=1 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg10_dmodemix_mnet_mlp1"


pfkube run --job-name=mstar-inv-reg-zero31-0 --gpu=1 --persist --cpu=8 --memory=48Gi --allow-overwrite --no-attach-logs -o nodeSelector="nvidia.k8s.pfn.io/gpu_model: Tesla-V100-SXM2-32GB" eval "cd /mnt/vol21/masomatics/ULASclone && pip install einops && pip install opencv-python && pip install scikit-image && python ./run.py --config_path=./configs/mnist/lstsq/neuralM.yml --attr batchsize=32 seed=1 max_iteration=150000 report_freq=1000 model_snapshot_freq=50000 manager_snapshot_freq=50000 num_workers=2 T_cond=2 T_pred=1 lr=0.0001 comm_reg=0 inv_reg=1.0 train_data.fn=./datasets/seq_mnist.py train_data.name=SequentialMNIST train_data.args.root=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST train_data.args.train=True train_data.args.T=3 train_data.args.max_T=9 train_data.args.max_angle_velocity_ratio=[-0.5,0.5] train_data.args.max_color_velocity_ratio=[-0.5,0.5] train_data.args.only_use_digit4=True train_data.args.backgrnd=False model.fn=./models/seqae.py model.name=SeqAENeuralM model.args.dim_m=256 model.args.dim_a=16 model.args.ch_x=3 model.args.k=4.0 model.args.dmode=mix model.args.mnet_mlp=2 training_loop.fn=./training_loops.py training_loop.name=loop_seqmodel training_loop.args.lr_decay_iter=140000 training_loop.args.reconst_iter=150000 log_dir=/mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/result/20220831_Mstar_inv_reg_0/lr00001_inv_reg10_dmodemix_mnet_mlp2"


