batchsize: 32
seed: 1
max_iteration: 1000000
report_freq: 1000
model_snapshot_freq: 1000000
manager_snapshot_freq: 1000
num_workers: 2
T_cond: 2
lr: 0.001 and 0.0001


train_data:
  fn: ./datasets/so3_data.py
  name: SO3rotationSequence
  args:
    data_filename: so3dat_sphere_Linear.pt and so3dat_sphere_iResNet.pt and so3dat_sphere_MLP.pt
    #data_filename: so3dat_sphere_Linear.pt
    train: True
    T: 3

model:
  fn: ./models/seqae.py
  name: SeqAELSTSQ_so3Net and SeqAELSTSQ_LinearNet
  args:
    dim_m: 10
    dim_a: 6
    ch_x: 1
    k: 2.
    predictive: True

training_loop:
  fn: ./training_loops.py
  name: loop_seqmodel
  args:
    lr_decay_iter: 900000
    reconst_iter: 0



