batchsize: 32
seed: 1
max_iteration: 50000
report_freq: 1000
model_snapshot_freq: 50000
manager_snapshot_freq: 50000
num_workers: 2
T_cond: 2
T_pred: 1
lr: 0.0003
reg:
  reg_bd: 0
  reg_orth: 0

train_data:
  fn: ./datasets/seq_mnist.py
  name: SequentialMNIST_double
  args:
    #root: /tmp/datasets/MNIST
    root: /mnt/nfs-mnj-hot-01/tmp/masomatics/block_diag/datasets/MNIST
    train: True
    T: 3
    max_T: 9
    max_angle_velocity_ratio: [-0.5, 0.5]
    max_color_velocity_ratio: [-0.5, 0.5]
    only_use_digit4: True
    backgrnd: False

model:
  fn: ./models/seqae.py
  name: SeqAELSTSQ
  args:
    dim_m: 256 and 312
    dim_a: 16
    ch_x: 3
    k: 2.
    predictive: True
    detachM: 0

training_loop:
  fn: ./training_loops.py
  name: loop_seqmodel
  args:
    lr_decay_iter: 40000
    reconst_iter: 0



